# empty Makefile.conf template

## OS X:
# BUILD=debug
# RADIANT_ABOUTMSG=Custom build
# EXE=ub
#
## MacPorts:
# CPPFLAGS=-I/opt/local/include/ -I/usr/X11R6/include/ 
# LDFLAGS=-L/opt/local/lib -L/usr/X11R6/lib
# MACLIBDIR=/opt/local/lib

## Fink
## (-arch ppc can combined with -arch 386, I read somewhere. However does work fine like this on OSX 10.6) 
# LDFLAGS=-arch i386
# CFLAGS=-arch i386
# TARGET_ARCH=-arch i386
# MACLIBDIR=/sw/lib
